name: contoller_app
description: Mobile application for OshElectro controllers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # UI Components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9

  # HTTP & API
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  url_launcher: ^6.3.0

  # Local Storage
  get_storage: ^2.1.1

  # Utils
  intl: ^0.18.1
  flutter_native_splash: ^2.3.8
  local_auth: ^2.1.8

  # UI Helpers
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0

  # Charts for statistics
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/mock/
    - assets/mock/news.json
    - assets/mock/notifications.json

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_24pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_24pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_24pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_24pt-Bold.ttf
          weight: 700